# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a021e2e061a71252221327784f6374f41fa2b7473bfe9b5861f8b22f2b47673487e78f5904353dcc08a6a7c1cb19200618045f28bb9111ddcdf4c76452539380

test:
  secret_key_base: e04a697b970144df6a5c3621401eb757c86811ece98649b0dc955bb86dfde5e6be5b6f217fc171b38c0001e390dd4db837adf3859353283b0fe911d19f7e8c6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
